name: kirkstone-nitrogen8m

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  kirkstone-fsl-image-multimedia:
  
    env:
      YOCTO_BRANCH: kirkstone
      MACHINE: nitrogen8m
      IMAGE: fsl-image-multimedia
      DISTRO: fslc-wayland
      
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/meta-flutter/ubuntu-20-dev:main
      options:
        --userns=keep-id -e USER_ID=$UID -e GROUP_ID=$GID
        --security-opt label=disable
        --tmpfs /tmp
        -w $PWD -v $PWD:$PWD
        -e SSH_AUTH_SOCK
        -v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
        -v /mnt/raid10/github-ci/download:/home/dev/dl
        -v /mnt/raid10/github-ci/sstate/yocto/kirkstone/imx8mmevk:/home/dev/sstate
        -v /mnt/raid10/github-ci/artifacts/imx8mmevk:/home/dev/artifacts

    steps:
    
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v3
        with:
          path: ''

      - name: Fetch poky
        run: |
          [ -d ../nitrogen8m-kirkstone ] || mkdir -p ../nitrogen8m-kirkstone
          cd ../nitrogen8m-kirkstone
          rm -rf sources || true
          ls -la
          git config --list
          git config --global user.email joel@winarske@gmail.com
          git config --global user.name "Joel Winarske"
          git config --list
          rm -rf conf | true
          /home/dev/bin/repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b ${{ env.YOCTO_BRANCH }}
          /home/dev/bin/repo sync --force-sync --no-clone-bundle -j `grep -c ^processor /proc/cpuinfo` &
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch https://github.com/kraj/meta-clang.git sources/meta-clang &
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch https://github.com/MarkusVolk/meta-wayland.git sources/meta-wayland &
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch https://git.yoctoproject.org/git/meta-selinux.git sources/meta-selinux &
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch https://git.yoctoproject.org/meta-virtualization sources/meta-virtualization &
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch https://git.yoctoproject.org/git/meta-security.git sources/meta-security &
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch https://github.com/meta-flutter/meta-flutter-vm.git sources/meta-flutter-vm &
          wait

      - name: Configure build
        shell: bash
        working-directory: ../nitrogen8m-kirkstone
        run: |
          rm -rf build/conf
          mkdir -p build/conf
          echo 'CONF_VERSION = "2"' > build/conf/local.conf
          echo 'ACCEPT_FSL_EULA = "1"' >> build/conf/local.conf
          DISTRO=${{ env.DISTRO }} MACHINE=${{ env.MACHINE }} source setup-environment build
          echo '***************************************'
          sed -i '/DL_DIR/d' ./conf/local.conf
          #
          echo 'INHERIT += "rm_work"' >> ./conf/local.conf
          echo 'DL_DIR = "/home/dev/dl"' >> conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> conf/local.conf
          #
          # Localization
          #
          echo 'DEFAULT_TIMEZONE = "America/Los_Angeles"' >> ./conf/local.conf
          echo 'ENABLE_BINARY_LOCALE_GENERATION = "1"' >> ./conf/local.conf
          echo 'IMAGE_LINGUAS:append = " en-us en-gb es-us"' >> ./conf/local.conf
          echo 'GLIBC_GENERATE_LOCALES:append = " en_US.UTF-8 es_US.UTF-8 en_GB.UTF-8"' >> ./conf/local.conf
          echo 'IMAGE_INSTALL:append = "\
              tzdata-core \
              tzdata-americas \
              "' >> ./conf/local.conf
          #
          # Baseline
          #
          echo 'DISTRO_FEATURES:append = " systemd wifi bluetooth usbhost"' >> ./conf/local.conf
          echo 'DISTRO_FEATURES:remove = "sysvinit x11 usbgadget ptest xen"' >> ./conf/local.conf
          echo 'INIT_MANAGER = "systemd"' >> ./conf/local.conf
          #
          # Wayland
          #
          echo 'DISTRO_FEATURES:append = " opengl wayland pam"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:append:pn-weston = " remoting"' >> ./conf/local.conf
          echo 'IMAGE_INSTALL:append = "\
              wlroots-tinywl \
              "' >> ./conf/local.conf
          #
          # Vulkan
          #
          echo 'DISTRO_FEATURES:remove = "vulkan"' >> conf/local.conf
          #
          # SELinux
          #
          echo 'DISTRO_FEATURES:append = " acl xattr pam selinux audit"' >> ./conf/local.conf
          echo 'PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mls"' >> ./conf/local.conf
          #
          # SECCOMP
          #
          echo 'DISTRO_FEATURES:append = " security seccomp"' >> ./conf/local.conf          
          #
          # Virtualization
          #
          echo 'DISTRO_FEATURES:append = " virtualization kvm"' >> ./conf/local.conf
          echo 'RUST_PANIC_STRATEGY = "abort"' >> ./conf/local.conf
          echo 'IMAGE_INSTALL:append = "\
              kvmtool dmidecode \
              libvirt libvirt-libvirtd libvirt-virsh \
              crosvm crosvm-direct crosvm-plugin \
              firecracker jailer curl \
              "' >> ./conf/local.conf
          #
          # Flutter
          #
          echo 'IMAGE_INSTALL:append = "\
              flutter-auto \
              packagegroup-flutter-test-apps \
              flutter-pi \
              "' >> ./conf/local.conf
          #
          # Kernel
          #
          echo 'LINUX_KERNEL_TYPE = "preempt-rt"' >> ./conf/local.conf
          echo 'PACKAGE_CLASSES = "package_ipk"' >> ./conf/local.conf
          echo '********** conf/local.conf **********'
          cat conf/local.conf
          echo '***************************************'
          bitbake-layers add-layer \
              ../sources/meta-clang \
              ../sources/meta-openembedded/meta-perl \
              ../sources/meta-openembedded/meta-networking \
              ../sources/meta-openembedded/meta-filesystems \
              ../sources/meta-security \
              ../sources/meta-selinux \
              ../sources/meta-virtualization \
              ../sources/meta-flutter-vm \
              ../sources/meta-wayland \
              ../../meta-flutter
          bitbake-layers show-layers
          echo '***************************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e ${{ env.IMAGE }} | grep "^DISTRO_FEATURES"
          bitbake -e ${{ env.IMAGE }} | grep "^IMAGE_FEATURES"
          echo '***************************************'
          bitbake -e > bb.environment
          bitbake -c do_cleansstate flutter-sdk-native

      - name: Build fsl-image-multimedia
        shell: bash
        working-directory: ../nitrogen8m-kirkstone
        run: |
          IMAGE=${{ env.IMAGE }}
          MACHINE=${{ env.MACHINE }}
          ARTIFACTS=/home/dev/artifacts
          DISTRO=${{ env.DISTRO }} MACHINE=${{ env.MACHINE }} source setup-environment build
          bitbake ${IMAGE} -c do_cleansstate
          bitbake ${IMAGE}
          rm -rf ${ARTIFACTS}/*
          cp bb.environment $ARTIFACTS
          cp tmp/deploy/images/${MACHINE}/${IMAGE}-${MACHINE}.wic.bz2 $ARTIFACTS

      - name: Publish SD card image artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.MACHINE }}-${{ env.IMAGE }}
          path: |
             /home/dev/artifacts/*
